### ISSUE TITLE
Remove Ax25 header with GNURadio

### ISSUE THREAD

**Issue by ryanpdx** [oresat/uniclogs-sdr#4]
It would be nice if uniclogs-sdr removed the AX25 header before send the message to Yamcs, so Yamcs doesn't have to deal with it.

**Comment by aSmig** [comment]
Do we still want this?

It is certainly doable. However, the AX.25 header may be helpful in identifying which vehicle or test platform the beacon is from. We should be able to tell from satellite_id and beacon_revision, but terrestrial test collisions have been an issue in the past.

**Comment by ryanpdx** [comment]
No, I forgot I even made this issue
